Revert "up luci-app-v2ray"
This reverts commit 8e10d4240a6a0d17e1602ab6c38df5d3e256385a.

diff --git a/luci/luci-app-v2ray/root/etc/init.d/v2ray b/luci/luci-app-v2ray/root/etc/init.d/v2ray
--- a/luci/luci-app-v2ray/root/etc/init.d/v2ray
+++ b/luci/luci-app-v2ray/root/etc/init.d/v2ray
@@ -17,7 +17,6 @@ IPSET_SRC_IGNORE_V4=v2ray_src_ignore_v4
 IPSET_SRC_IGNORE_V6=v2ray_src_ignore_v6
 IPSET_DST_PROXY_V4=v2ray_dst_proxy_v4
 IPSET_DST_PROXY_V6=v2ray_dst_proxy_v6
-IPSET_SRC_DIRECT_V4=v2ray_src_direct_v4
 IPSET_DST_DIRECT_V4=v2ray_dst_direct_v4
 IPSET_DST_DIRECT_V6=v2ray_dst_direct_v6
 
@@ -31,7 +30,15 @@ TRANSPARENT_PROXY_ADDITION=
 
 DNSMASQ_RESTART_EXPECTED=0
 
-. /usr/share/libubox/jshn.sh
+if [ -r /usr/share/libubox/jshn.sh ] ; then
+	. /usr/share/libubox/jshn.sh
+elif [ -r /lib/functions/jshn.sh ] ; then
+	. /lib/functions/jshn.sh
+else
+	logger -p daemon.err -t "$NAME" "Package required: jshn."
+	echo "[err] Package required: jshn." >&2
+	exit 1
+fi
 
 _log() {
 	local level="$1" ; shift
@@ -81,7 +88,7 @@ get_file_content() {
 	test -n "$filename" || return
 	test -r "/etc/v2ray/${filename}.txt" || return
 
-	cat "/etc/v2ray/${filename}.txt" | grep -v "^$" | grep -v "^#"
+	cat "/etc/v2ray/${filename}.txt" | grep -v "^$"
 }
 
 append_server_ipv4() {
@@ -137,7 +144,6 @@ v2ray_section_validate() {
 		'enabled:bool:0' \
 		'v2ray_file:string' \
 		'asset_location:directory' \
-		'mem_percentage:and(uinteger, max(100)):80' \
 		'config_file:file' \
 		'loglevel:or("debug", "info", "warning", "error", "none")' \
 		'access_log:string' \
@@ -161,8 +167,7 @@ dns_server_section_validate() {
 	uci_validate_section "$NAME" "dns_server" "$1" \
 		'address:string' \
 		'port:port' \
-		'domains:list(string)' \
-		'expect_ips:list(string)'
+		'domains:list(string)'
 }
 
 routing_section_validate() {
@@ -390,7 +395,6 @@ add_v2ray_redirect_rules() {
 
 	local port="$TRANSPARENT_PROXY_PORT"
 	local addition="$TRANSPARENT_PROXY_ADDITION"
-	local ipset_src_direct="$IPSET_SRC_DIRECT_V4"
 	local ipset_dst_direct="$IPSET_DST_DIRECT_V4"
 
 	test -n "$port" || return
@@ -399,7 +403,6 @@ add_v2ray_redirect_rules() {
 		*nat
 		:V2RAY -
 		-A V2RAY -p tcp -j RETURN -m mark --mark 0xff
-		-A V2RAY -p tcp -j RETURN -m set --match-set $ipset_src_direct src
 		-A V2RAY -p tcp -j RETURN -m set --match-set $ipset_dst_direct dst
 		-A V2RAY -p tcp $ext_args -j REDIRECT --to-ports $port
 		$(
@@ -454,7 +457,6 @@ add_v2ray_redirect_rules() {
 
 			:V2RAY_MARK -
 			-A V2RAY_MARK -p udp -j RETURN -m mark --mark 0xff
-			-A V2RAY_MARK -p udp -j RETURN -m set --match-set $ipset_src_direct src
 			-A V2RAY_MARK -p udp -j RETURN -m set --match-set $ipset_dst_direct dst
 			$(
 				if [ "$addition" = "dns" ] ; then
@@ -476,7 +478,6 @@ add_v2ray_tproxy_rules() {
 
 	local port="$TRANSPARENT_PROXY_PORT"
 	local addition="$TRANSPARENT_PROXY_ADDITION"
-	local ipset_src_direct="$IPSET_SRC_DIRECT_V4"
 	local ipset_dst_direct="$IPSET_DST_DIRECT_V4"
 
 	test -n "$port" || return
@@ -498,7 +499,6 @@ add_v2ray_tproxy_rules() {
 				done
 			fi
 		)
-		-A V2RAY -j RETURN -m set --match-set $ipset_src_direct src
 		-A V2RAY -j RETURN -m set --match-set $ipset_dst_direct dst
 		-A V2RAY -p tcp $ext_args -j TPROXY --on-port $port --tproxy-mark 0x1/0x1
 		$(
@@ -524,7 +524,6 @@ add_v2ray_tproxy_rules() {
 
 		:V2RAY_MASK -
 		-A V2RAY_MASK -j RETURN -m mark --mark 0xff
-		-A V2RAY_MASK -j RETURN -m set --match-set $ipset_src_direct src
 		-A V2RAY_MASK -j RETURN -m set --match-set $ipset_dst_direct dst
 		-A V2RAY_MASK -p tcp $ext_args -j MARK --set-mark 1
 		$(
@@ -598,7 +597,6 @@ create_v2ray_ipset() {
 		create $IPSET_SRC_IGNORE_V6 hash:ip hashsize 64 family inet6 timeout 0
 		create $IPSET_DST_PROXY_V4 hash:net hashsize 64 family inet timeout 604800
 		create $IPSET_DST_PROXY_V6 hash:net hashsize 64 family inet6 timeout 604800
-		create $IPSET_SRC_DIRECT_V4 hash:net hashsize 64 family inet timeout 0
 		create $IPSET_DST_DIRECT_V4 hash:net hashsize 64 family inet timeout 604800
 		create $IPSET_DST_DIRECT_V6 hash:net hashsize 64 family inet6 timeout 604800
 		$(echo "$reserved_v4" | sed "s/.*/add $IPSET_DST_DIRECT_V4 & timeout 0/")
@@ -624,69 +622,53 @@ init_rules_for_listfile() {
 	local direct_content
 	direct_content="$(get_file_content "directlist")"
 
-	if [ -n "$direct_content" ] ; then
-		echo "$direct_content" | \
-			grep -oE "[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?" | \
-			sed "s/.*/add $IPSET_DST_DIRECT_V4 & timeout 0/" | \
-			ipset -! restore 2>/dev/null
+	echo "$direct_content" | \
+		grep -oE "[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?" | \
+		sed "s/.*/add $IPSET_DST_DIRECT_V4 & timeout 0/" | \
+		ipset -! restore 2>/dev/null
 
-		echo "$direct_content" | \
-			grep -oE "([0-9a-fA-F]{0,4}:){1,7}([0-9a-fA-F]){0,4}(/[0-9]{1,2})?" | \
-			sed "s/.*/add $IPSET_DST_DIRECT_V6 & timeout 0/" | \
-			ipset -! restore 2>/dev/null
+	echo "$direct_content" | \
+		grep -oE "([0-9a-fA-F]{0,4}:){1,7}([0-9a-fA-F]){0,4}(/[0-9]{1,2})?" | \
+		sed "s/.*/add $IPSET_DST_DIRECT_V6 & timeout 0/" | \
+		ipset -! restore 2>/dev/null
 
-		if [ -n "$direct_list_dns" ] ; then
-			echo "$direct_content" | \
-				grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
-				sed "s|.*|server=/&/$direct_list_dns\nipset=/&/$IPSET_DST_DIRECT_V4,$IPSET_DST_DIRECT_V6|" \
-				>>"$FILE_V2RAY_DNSMASQ_CACHE"
-		else
-			echo "$direct_content" | \
-				grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
-				sed "s|.*|ipset=/&/$IPSET_DST_DIRECT_V4,$IPSET_DST_DIRECT_V6|" \
-				>>"$FILE_V2RAY_DNSMASQ_CACHE"
-		fi
+	if [ -n "$direct_list_dns" ] ; then
+		echo "$direct_content" | \
+			grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
+			sed "s|.*|server=/&/$direct_list_dns\nipset=/&/$IPSET_DST_DIRECT_V4,$IPSET_DST_DIRECT_V6|" \
+			>>"$FILE_V2RAY_DNSMASQ_CACHE"
+	else
+		echo "$direct_content" | \
+			grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
+			sed "s|.*|ipset=/&/$IPSET_DST_DIRECT_V4,$IPSET_DST_DIRECT_V6|" \
+			>>"$FILE_V2RAY_DNSMASQ_CACHE"
 	fi
 
 	# For proxy list
 	local proxy_content
 	proxy_content="$(get_file_content "proxylist")"
 
-	if [ -n "$proxy_content" ] ; then
+	echo "$proxy_content" | \
+		grep -oE "[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?" | \
+		sed "s/.*/add $IPSET_DST_PROXY_V4 & timeout 0/" | \
+		ipset -! restore 2>/dev/null
+
+	echo "$proxy_content" | \
+		grep -oE "([0-9a-fA-F]{0,4}:){1,7}([0-9a-fA-F]){0,4}(/[0-9]{1,2})?" | \
+		sed "s/.*/add $IPSET_DST_PROXY_V6 & timeout 0/" | \
+		ipset -! restore 2>/dev/null
+
+	if [ -n "$proxy_list_dns" ] ; then
 		echo "$proxy_content" | \
-			grep -oE "[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?" | \
-			sed "s/.*/add $IPSET_DST_PROXY_V4 & timeout 0/" | \
-			ipset -! restore 2>/dev/null
-
+			grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
+			sed "s|.*|server=/&/$proxy_list_dns\nipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
+			>>"$FILE_V2RAY_DNSMASQ_CACHE"
+	else
 		echo "$proxy_content" | \
-			grep -oE "([0-9a-fA-F]{0,4}:){1,7}([0-9a-fA-F]){0,4}(/[0-9]{1,2})?" | \
-			sed "s/.*/add $IPSET_DST_PROXY_V6 & timeout 0/" | \
-			ipset -! restore 2>/dev/null
-
-		if [ -n "$proxy_list_dns" ] ; then
-			echo "$proxy_content" | \
-				grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
-				sed "s|.*|server=/&/$proxy_list_dns\nipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
-				>>"$FILE_V2RAY_DNSMASQ_CACHE"
-		else
-			echo "$proxy_content" | \
-				grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
-				sed "s|.*|ipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
-				>>"$FILE_V2RAY_DNSMASQ_CACHE"
-		fi
+			grep -oE "([0-9a-zA-Z_-]+\.)+[a-zA-Z]{2,}$" | \
+			sed "s|.*|ipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
+			>>"$FILE_V2RAY_DNSMASQ_CACHE"
 	fi
-
-  # For local devices outbound list
-	local src_content
-	src_content="$(get_file_content "srcdirectlist")"
-
-	if [ -n "$src_content" ] ; then
-		echo "$src_content" | \
-			grep -oE "[0-9]{1,3}(\.[0-9]{1,3}){3}(/[0-9]{1,2})?" | \
-			sed "s/.*/add $IPSET_SRC_DIRECT_V4 & timeout 0/" | \
-			ipset -! restore 2>/dev/null
-	fi
-
 }
 
 gracefully_restart_dnsmasq() {
@@ -742,7 +724,7 @@ add_dns_settings() {
 					continue
 				fi
 
-				if [ -z "${port}${domains}${expect_ips}" ] ; then
+				if [ -z "$port" ] && [ -z "$domains" ] ; then
 					json_add_string "" "$address"
 				else
 					json_add_object ""
@@ -763,17 +745,6 @@ add_dns_settings() {
 						done
 
 						json_close_array # domains
-					fi
-
-					if [ -n "$expect_ips" ] ; then
-						json_add_array "expectIPs"
-
-						local e
-						for e in $expect_ips ; do
-							json_add_string "" "$e"
-						done
-
-						json_close_array # expectIPs
 					fi
 
 					json_close_object
@@ -1947,56 +1918,30 @@ setup_transparent_proxy() {
 	local ext_args
 	case "${proxy_mode:-default}" in
 		"cn_direct")
-			local chnroute="$(get_file_content "chnroute")"
-			local chnroute6="$(get_file_content "chnroute6")"
-
-			if [ -n "$chnroute" ] ; then
-				ipset -! restore <<-EOF 2>/dev/null
-					$(echo "$chnroute" | sed "s/.*/add $IPSET_DST_DIRECT_V4 & timeout 0/")
-				EOF
-			fi
-
-			if [ -n "$chnroute6" ] ; then
-				ipset -! restore <<-EOF 2>/dev/null
-					$(echo "$chnroute6" | sed "s/.*/add $IPSET_DST_DIRECT_V6 & timeout 0/")
-				EOF
-			fi
-
+			ipset -! restore <<-EOF 2>/dev/null
+				$(get_file_content "chnroute" | sed "s/.*/add $IPSET_DST_DIRECT_V4 & timeout 0/")
+				$(get_file_content "chnroute6" | sed "s/.*/add $IPSET_DST_DIRECT_V6 & timeout 0/")
+			EOF
 			ext_args=
 			;;
 		"cn_proxy")
-			local chnroute="$(get_file_content "chnroute")"
-			local chnroute6="$(get_file_content "chnroute6")"
-
-			if [ -n "$chnroute" ] ; then
-				ipset -! restore <<-EOF 2>/dev/null
-					$(echo "$chnroute" | sed "s/.*/add $IPSET_DST_PROXY_V4 & timeout 0/")
-				EOF
-			fi
-
-			if [ -n "$chnroute6" ] ; then
-				ipset -! restore <<-EOF 2>/dev/null
-					$(echo "$chnroute6" | sed "s/.*/add $IPSET_DST_PROXY_V6 & timeout 0/")
-				EOF
-			fi
-
+			ipset -! restore <<-EOF 2>/dev/null
+				$(get_file_content "chnroute" | sed "s/.*/add $IPSET_DST_PROXY_V4 & timeout 0/")
+				$(get_file_content "chnroute6" | sed "s/.*/add $IPSET_DST_PROXY_V6 & timeout 0/")
+			EOF
 			ext_args="-m set --match-set $IPSET_DST_PROXY_V4 dst"
 			;;
 		"gfwlist_proxy")
 			local gfwlist="$(get_file_content "gfwlist")"
-
-			if [ -n "$gfwlist" ] ; then
-				if [ -n "$proxy_list_dns" ] ; then
-					echo "$gfwlist" | \
-						sed "s|.*|server=/&/$proxy_list_dns\nipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
-						>> "$FILE_V2RAY_DNSMASQ_CACHE"
-				else
-					echo "$gfwlist" | \
-						sed "s|.*|ipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
-						>> "$FILE_V2RAY_DNSMASQ_CACHE"
-				fi
+			if [ -n "$proxy_list_dns" ] ; then
+				echo "$gfwlist" | \
+					sed "s|.*|server=/&/$proxy_list_dns\nipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
+					>> "$FILE_V2RAY_DNSMASQ_CACHE"
+			else
+				echo "$gfwlist" | \
+					sed "s|.*|ipset=/&/$IPSET_DST_PROXY_V4,$IPSET_DST_PROXY_V6|" \
+					>> "$FILE_V2RAY_DNSMASQ_CACHE"
 			fi
-
 			ext_args="-m set --match-set $IPSET_DST_PROXY_V4 dst"
 			;;
 		*)
@@ -2188,18 +2133,8 @@ start_instance() {
 		procd_set_param env V2RAY_LOCATION_ASSET="$asset_location"
 	fi
 
-	# cat /proc/PID/limits to see if limits works
 	procd_set_param limits nofile="102400 102400"
-	procd_append_param limits core="0 0"
-
-	if [ "$mem_percentage" -gt "0" ] ; then
-		local mem_total="$(awk '/MemTotal/ {print $2}' /proc/meminfo)"
-		if [ -n "$mem_total" ] ; then
-			local use_mem="$(expr $mem_total \* $mem_percentage \* 10)"
-			procd_append_param limits as="$use_mem $use_mem"
-		fi
-	fi
-
+	procd_append_param limits core="unlimited"
 	procd_set_param file "$temp_config"
 	procd_set_param stderr 1 # forward stderr of the command to logd
 	procd_set_param stdout 1
